faq/urls.py
from django.contrib import admin
from django.urls import path

import faq
from faq import views
urlpatterns = [
    path('', faq.views.exibePaginaFAQ, name='faq')
]

kazumaStore/urls.py
from django.contrib import admin
from django.urls import path, include

from produtos import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produtos.urls')),
    path('sobre', include('sobre.urls')),
    path('faq/', include('faq.urls')),
    path('proximosLancamentos/', include('proximosLancamentos.urls')),
    path('', include('login.urls'))
]

produtos/urls.py
from django.contrib import admin
from django.urls import path

from produtos.views import AdministradorProdutosCadastrar, AdministradorProdutosAlterar, AdministradorProdutosDeletar
import produtos
from produtos import views
urlpatterns = [
    path('', views.index, name=''),
    path('adm_produtos', AdministradorProdutosCadastrar.as_view(), name='admProdutosCadastrar'),
    path(r'^adm_produtos(?P<pk>[0-9]+)', AdministradorProdutosAlterar.as_view(), name='admProdutosAlterar'),
    path(r'^adm_produtos/deletar/(?P<pk>[0-9]+)', AdministradorProdutosDeletar.as_view(), name='admProdutosDeletar'),
    path('adm_produtos/busca', views.buscar, name='buscar'),
    path(r'^comprar/(?P<produtoId>[0-9]+)', views.comprar, name='comprar'),
    path('carrinho', views.carrinho, name='carrinho'),
    path('carrinho/alterarQuantidadeAjax/', views.alterarQuantidadeAjax, name='alterarQuantidadeAjax'),
    path('carrinho/deletarProdutoAjax/', views.deletarProdutoDoCarrinhoAjax, name='deletarProdutoDoCarrinhoAjax')
]

produtos/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Produto(models.Model):

    nome = models.CharField(max_length=99999, null=False)
    descricao = models.CharField(max_length=99999, null=False)
    preco = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    foto = models.CharField(max_length=99999)
    classe = models.CharField(max_length=99999)

class Carrinho(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    def comprar(self,produtoId,quantidade):
        produtoComprado = Produto.objects.get(id=produtoId)

        try:
            itemCarrinho = ItemCarrinho.objects.get(carrinho=self,produto=produtoComprado)
            itemCarrinho.quantidade +=quantidade
            itemCarrinho.save()
        except ItemCarrinho.DoesNotExist:
            ItemCarrinho(produto=Produto.objects.get(id=produtoId),quantidade=quantidade,carrinho=self).save()

    def alterarQuantidade(self,produtoId,quantidade):
        produtoComprado = Produto.objects.get(id=produtoId)
        itemCarrinho = ItemCarrinho.objects.get(carrinho=self, produto=produtoComprado)
        itemCarrinho.quantidade = quantidade
        itemCarrinho.save()

    def deletarProduto(self,produtoId):
        produtoComprado = Produto.objects.get(id=produtoId)
        itemCarrinho = ItemCarrinho.objects.get(carrinho=self, produto=produtoComprado)
        itemCarrinho.delete()

    def retornaTodosItensDoCarrinho(self):
        return ItemCarrinho.objects.filter(carrinho_id=self.id)

class ItemCarrinho(models.Model):
    produto = models.ForeignKey('Produto', on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(default=0)
    carrinho = models.ForeignKey(Carrinho, related_name='itensCarrinho', on_delete=models.CASCADE)

produtos/forms.py
from django import forms
from produtos.models import Produto
class CadastrarProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'descricao', 'preco', 'foto', 'classe']

    def is_valid(self):
        valid = True

        if not super(CadastrarProdutoForm, self).is_valid() or \
                float(self.data['preco']) < 0 or \
                self.data['foto'][:26] != 'static/kazumaStore/images/' or \
                (self.data['classe'] != 'card text-center anime' and self.data['classe'] != 'card text-center figure'):

            self.adiciona_erro('Verificar os dados inseridos!')
            valid = False

        return valid

    def adiciona_erro(self, message):
        erro = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        erro.append(message)

produtos/views.py
import numpy
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.core.paginator import Paginator
# Create your views here.
from produtos.models import Produto, Carrinho
from produtos.forms import CadastrarProdutoForm

@login_required
def index(request):
    return render(request, 'produtos.html', {"produtos" : Produto.objects.all()})

@login_required
def comprar(request, produtoId):
    carrinhoDoUsuarioLogado = getCarrinhoPerfilLogado(request)
    carrinhoDoUsuarioLogado.comprar(produtoId,int(request.POST['quantidade']))
    return render(request, 'carrinho.html', retornaDadosCarrinho(request))

@login_required
def carrinho(request):
    return render(request, 'carrinho.html', retornaDadosCarrinho(request))

@login_required
def alterarQuantidadeAjax(request):
    produtoId = int(request.POST['produtoId'])
    quantidade = int(request.POST['quantidade'])
    getCarrinhoPerfilLogado(request).alterarQuantidade(produtoId,quantidade)
    return render(request, 'carrinho.html', retornaDadosCarrinho(request))

@login_required
def deletarProdutoDoCarrinhoAjax(request):
    produtoId = int(request.POST['produtoId'])
    getCarrinhoPerfilLogado(request).deletarProduto(produtoId)
    return render(request, 'carrinho.html', retornaDadosCarrinho(request))

def retornaDadosCarrinho(request):
    carrinhoDoUsuarioLogado = getCarrinhoPerfilLogado(request)
    todosOsItensDoCarrinho = carrinhoDoUsuarioLogado.retornaTodosItensDoCarrinho()
    precoTotalDosItensDoCarrinho = calculaPrecoTotalDosItensDoCarrinho(todosOsItensDoCarrinho)
    return {"itensCarrinho": zip(todosOsItensDoCarrinho, precoTotalDosItensDoCarrinho),
                                                "precoTotalCarrinho":numpy.sum(precoTotalDosItensDoCarrinho)}

def calculaPrecoTotalDosItensDoCarrinho(itens):
    precosTotais = []
    for item in itens:
        precosTotais.append(item.quantidade*item.produto.preco)
    return precosTotais

@login_required
def getCarrinhoPerfilLogado(request):
    try:
        carrinhoUsuarioLogado = Carrinho.objects.get(usuario=request.user)

    except Carrinho.DoesNotExist:
        carrinhoUsuarioLogado = Carrinho(request.user.id)
        carrinhoUsuarioLogado.save()
    return carrinhoUsuarioLogado

def buscar(request):
    todosOsProdutosBuscaAlterar = Produto.objects.all()
    todosOsProdutosBuscaExcluir = Produto.objects.all()

    if 'buscaAlterar' in request.GET:
        nomeBuscado = request.GET['buscaAlterar']

        if buscar:
            todosOsProdutosBuscaAlterar = todosOsProdutosBuscaAlterar.filter(nome__icontains=nomeBuscado)
            return render(request, 'produtosAdministracaoBusca.html', {"produtosAlterar": todosOsProdutosBuscaAlterar,
                                                                       "produtosExcluir": todosOsProdutosBuscaExcluir,
                                                                       "collapse":['',' in show ','']})

    if 'buscaExcluir' in request.GET:
        nomeBuscado = request.GET['buscaExcluir']

        if buscar:
            todosOsProdutosBuscaExcluir = todosOsProdutosBuscaExcluir.filter(nome__icontains=nomeBuscado)
            return render(request, 'produtosAdministracaoBusca.html', {"produtosAlterar" : todosOsProdutosBuscaAlterar,
                                                                        "produtosExcluir" : todosOsProdutosBuscaExcluir,
                                                                        "collapse":['','',' in show ']})
def paginacao(request):
    produtos = Produto.objects.all()
    produtosPaginados = Paginator(produtos, 1)
    pagina = request.GET.get('pagina')
    produtos = produtosPaginados.get_page(pagina)
    return produtos;

def collapsePaginacao(request):
    collapse = [' in show ', '', '']
    if "formularioAlterarProduto" in str(request.GET.get('idTag')):
        collapse[1] = ' in show '
    elif "formularioExcluirProduto" in str(request.GET.get('idTag')):
        collapse[2] = ' in show '
    return collapse

class AdministradorProdutosCadastrar(View):

    template_name = 'produtosAdministracao.html'

    def get(self, request):
        collapse = collapsePaginacao(request)
        return render(request, self.template_name, {"produtos": paginacao(request), "collapse": collapse})

    def post(self, request):
        form = CadastrarProdutoForm(request.POST)

        if form.is_valid():

            novoProduto = Produto(nome= form.data['nome'], descricao= form.data['descricao'], preco= form.data['preco'],
                                  foto= form.data['foto'], classe= form.data['classe'])
            novoProduto.save()

            return redirect('')

        return render(request, self.template_name, { 'form': form, "produtos" : Produto.objects.all() })

class AdministradorProdutosAlterar(View):

    template_name = 'produtosAdministracao.html'

    def get(self, request):
        collapse = collapsePaginacao(request)
        return render(request, self.template_name, {"produtos": paginacao(request), "collapse": collapse})

    def post(self, request, pk):

        produtoAlterado = Produto.objects.get(pk=pk);
        form = CadastrarProdutoForm(request.POST, instance=produtoAlterado)

        if form.is_valid():

            form.save();

            return redirect('')

        return render(request, self.template_name, { 'form': form,"produtos" : Produto.objects.all() })

class AdministradorProdutosDeletar(View):

    template_name = 'produtosAdministracao.html'

    def get(self, request):
        collapse = collapsePaginacao(request)
        return render(request, self.template_name, {"produtos": paginacao(request), "collapse": collapse})

    def post(self, request, pk):

        produtoDeletado = Produto.objects.get(pk=pk);
        produtoDeletado.delete()

        return redirect('')

produtos/templates/partials/buscaAlterar.html
{% load static %}

<form action="{% url 'buscar' %}#navbar" class="input-group">
            <input type="text" name="buscaAlterar" class="form-control " placeholder="Digite o nome do produto para alterar">
            <button type="submit" class="btn btn-outline-secondary"><i class="fa fa-search"></i></button>
        </form>

produtos/templates/partials/buscaExcluir.html
{% load static %}

 <form action="{% url 'buscar' %}#navbar" class="input-group">
            <input type="text" name="buscaExcluir" class="form-control " placeholder="Digite o nome do produto para excluir">
            <button type="submit" class="btn btn-outline-secondary" ><i class="fa fa-search"></i></button>
        </form>

produtos/templates/partials/errosFormulario.html
{% load static %}

{% if form.errors %}
    <div class="alert alert-danger container mt-2 mb-2" role="alert">
        <button  type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{ form.non_field_errors }}
    </div>
{% endif %}

produtos/templates/partials/formularioAlterarProduto.html
{% load static %}

<form action="{% url 'admProdutosAlterar' produto.id %}#navbar" method="post" class="border border-warning rounded py-3 px-3 mt-2 container mt-1 mb-3 card">
                {% csrf_token %}
                <div class="form-group row">
                    <label>Nome: </label>
                    <input name="nome" required id="id_nome" class="form-control col-sm-10 ml-2" type="text" value="{{produto.nome}}">
                </div>
                <div class="form-group row">
                    <label>Descrição: </label>
                    <input name="descricao" required id="id_descricao" class="form-control col-sm-10 ml-2" type="text" value="{{produto.descricao}}">
                </div>
                <div class="form-group row">
                    <label>Foto: </label>
                    <input name="foto" required id="id_foto" class="form-control col-sm-10 ml-2" type="text" value="{{produto.foto}}">
                </div>
                <div class="form-group row">
                    <label>Classe: </label>
                    <input name="classe" required id="id_classe" class="form-control col-sm-10 ml-2" type="text" value="{{produto.classe}}">
                </div>
                <div class="form-group row">
                    <label>Preço: </label>
                    <input name="preco" step="any" required id="id_preco" class="form-control col-sm-10 ml-2" type="number" value="{{produto.preco}}" >
                </div>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Alterar</button>
                </div>
            </form>

produtos/templates/partials/formularioCadastrarProduto.html
{% load static %}

{% csrf_token %}
<div class="form-group">
    <label>Nome</label>
    <input name="nome" required id="id_nome" type="text" class="form-control" placeholder="Digite o nome do produto a ser adicionado">
</div>

<div class="form-group">
    <label>Descrição</label>
    <input type="text" name="descricao" required id="id_descricao" class="form-control" placeholder="Digite a descrição do produto a ser adicionado">
</div>

<div class="form-group">
    <label>Foto</label>
    <input name="foto" required id="id_foto" type="text" class="form-control" placeholder="Digite o endereço da foto do produto a ser adicionado">
</div>
<div class="form-group">
    <label>Classe</label>
    <input name="classe" required id="id_classe" type="text" class="form-control" placeholder="A classe de css do produto a ser adicionado">
</div>

<div class="form-row align-items-center">
    <label class="mr-2">Preço: </label>
    <input name="preco" step="any" required id="id_preco" class="form-control" type="number" style="width: 100px;">
</div>


<div class="text-right">
    <button type="submit" class="btn btn-primary">Cadastrar</button>
</div>

produtos/templates/partials/formularioExcluirProduto.html
{% load static %}

<div class="border rounded py-3 px-3 mt-2 container mt-1 mb-3 card" style="border-color: brown !important;">
    <p><b>Nome: </b>{{ produto.nome }}</p>
    <p><b>Descrição: </b>{{ produto.descricao }}</p>
    <p><b>Preço: </b>{{ produto.preco }}</p>
    <form action="{% url 'admProdutosDeletar' produto.id %}#navbar" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-block">Excluir</button>
    </form>
</div>

produtos/templates/partials/paginacao.html
{% load static %}

{% if produtos.has_previous %}
    <a name="teste" href="?pagina=1&idTag={{ idTag }}#{{ idTag }}"><<</a>
    <a href="?pagina={{ produtos.previous_page_number }}&idTag={{ idTag }}#{{ idTag }}"><</a>
{% endif %}
{% for pagina in produtos.paginator.page_range %}
    {% if produtos.number == pagina %}
        <strong>{{pagina}}</strong>
    {% elif pagina > produtos.number|add:'-3' and pagina < produtos.number|add:'3' %}
        {{ pagina }}
    {% endif %}
{% endfor %}
{% if produtos.has_next %}
    <a href="?pagina={{ produtos.next_page_number }}&idTag={{ idTag }}#{{ idTag }}">></a>
    <a href="?pagina={{ produtos.paginator.num_pages }}&idTag={{ idTag }}#{{ idTag }}">>></a>
{% endif %}